source "https://rubygems.org"

gem 'sinatra', '2.0.0.beta.2'
gem 'service_manager', '0.6.4'
gem 'activerecord', '5.0.0.1'
gem 'sqlite3', '1.3.11'

group :development do
  gem 'rspec', '3.5.0'
  gem 'cucumber', '3.0.0.pre.1'
  gem 'capybara', '2.9.1'
  gem 'launchy', '2.4.3'
  #START_HIGHLIGHT
  gem 'database_cleaner', '1.5.3'
  #END_HIGHLIGHT
end

