source "https://rubygems.org"

gem 'sinatra', '2.0.0.beta.2'
gem 'service_manager', '0.6.4'
#START_HIGHLIGHT
gem 'activerecord', '5.0.0.1'
gem 'sqlite3', '1.3.11'
#END_HIGHLIGHT

group :development do
  gem 'rspec', '3.5.0'
  gem 'cucumber', '3.0.0.pre.1'
  gem 'capybara', '2.9.1'
  gem 'launchy', '2.4.3'
end

