# This Gemfile lists all Gems used throughout the book - with versions.
source "https://rubygems.org"

# Build stuff
gem 'bundler', '1.13.1'
gem "rake", "11.3.0"
gem 'watchr', '0.7'
gem 'bcat', '0.6.2', git: 'https://github.com/tooky/bcat.git',
                     branch: 'allow-rack-2'

# General stuff
gem 'aruba', '0.14.2'
gem 'cucumber', '3.0.0.pre.1'
gem 'rspec', '3.5.0'

# Rails stuff
gem 'activerecord', '5.0.0.1'
gem 'capybara', '2.9.1'
gem 'coffee-rails', '4.2.1'
gem 'cucumber-rails', '1.4.4'
gem 'database_cleaner', '1.5.3'
gem 'factory_girl', '4.7.0'
gem 'jquery-rails', '4.2.1'
gem 'launchy', '2.4.3'
gem 'rails', '5.0.0.1'
gem 'rspec-rails', '3.5.2'
gem 'sass-rails', '5.0.6'
gem 'sqlite3', '1.3.11'
gem 'uglifier', '3.0.2'

# Non Rails stuff
gem 'childprocess', '0.5.9'
gem 'httparty', '0.14.0'
gem 'json', '2.0.2'
gem 'rack-test', '0.6.3'
gem 'service_manager', '0.6.4'
gem 'sinatra', '2.0.0.beta.2'

